default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: personal_site_development

test:
  <<: *default
  database: personal_site_test

production:
  <<: *default
  database: personal_site_production
  username: personal_site
  password: <%= ENV['PERSONAL_SITE_DATABASE_PASSWORD'] %>